net:
  address: 127.0.0.1
  game_port: 43594
  ondemand_port: 43594
  jaggrab_port: 43595
  http_port: 80
cache:
  cacheDir: .377cache
  jaggrabEnabled: false
rsa:
  rsaPub: 65537
  rsaModulus: 170266381807335046121774073514220583891686029487165562794998484549236036467227923571770256617931840775621072487838687650522710227973331693237285456731778528244126984080232314114323601116304887478969296070648644633713088027922830600712492972687351204275625149978223159432963210789506993409208545916714905193639
login:
  useStaticCredentials: true
  username: Promises
  password: Testing
game:
  roofsEnabled: true
  freeTeleports: true
